version: '3.8'

services:
  postgres:
    image: App
    container_name: pegasus
    environment:
      POSTGRES_DB: testroot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
