version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
    - my_network
  app:
    image: my-django-app:latest
    networks:
      - my_network
  db:
    image: postgres:latest
    networks:
      - my_network
    environment:
      POSTGRES_DB: testroot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
networks:
  my_network:
