version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testroot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    networks:
      - my_network

